package com.example.design.common.domain;

import java.util.List;

public class Bookshelf {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookshelf.shelfid
     *
     * @mbg.generated Sun Dec 08 11:15:03 CST 2019
     */
    private Integer shelfid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookshelf.book_id
     *
     * @mbg.generated Sun Dec 08 11:15:03 CST 2019
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookshelf.telephone
     *
     * @mbg.generated Sun Dec 08 11:15:03 CST 2019
     */
    private String telephone;

    private List<Book> bookList;

    public List<Book> getBookList() {
        return bookList;
    }

    public void setBookList(List<Book> bookList) {
        this.bookList = bookList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookshelf.shelfid
     *
     * @return the value of bookshelf.shelfid
     *
     * @mbg.generated Sun Dec 08 11:15:03 CST 2019
     */
    public Integer getShelfid() {
        return shelfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookshelf.shelfid
     *
     * @param shelfid the value for bookshelf.shelfid
     *
     * @mbg.generated Sun Dec 08 11:15:03 CST 2019
     */
    public void setShelfid(Integer shelfid) {
        this.shelfid = shelfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookshelf.book_id
     *
     * @return the value of bookshelf.book_id
     *
     * @mbg.generated Sun Dec 08 11:15:03 CST 2019
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookshelf.book_id
     *
     * @param bookId the value for bookshelf.book_id
     *
     * @mbg.generated Sun Dec 08 11:15:03 CST 2019
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookshelf.telephone
     *
     * @return the value of bookshelf.telephone
     *
     * @mbg.generated Sun Dec 08 11:15:03 CST 2019
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookshelf.telephone
     *
     * @param telephone the value for bookshelf.telephone
     *
     * @mbg.generated Sun Dec 08 11:15:03 CST 2019
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }
}