package com.example.design.common.domain;

import java.util.ArrayList;
import java.util.List;

public class BookExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public BookExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table book
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBookIdIsNull() {
            addCriterion("book_id is null");
            return (Criteria) this;
        }

        public Criteria andBookIdIsNotNull() {
            addCriterion("book_id is not null");
            return (Criteria) this;
        }

        public Criteria andBookIdEqualTo(Integer value) {
            addCriterion("book_id =", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdNotEqualTo(Integer value) {
            addCriterion("book_id <>", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdGreaterThan(Integer value) {
            addCriterion("book_id >", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("book_id >=", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdLessThan(Integer value) {
            addCriterion("book_id <", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdLessThanOrEqualTo(Integer value) {
            addCriterion("book_id <=", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdIn(List<Integer> values) {
            addCriterion("book_id in", values, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdNotIn(List<Integer> values) {
            addCriterion("book_id not in", values, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdBetween(Integer value1, Integer value2) {
            addCriterion("book_id between", value1, value2, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdNotBetween(Integer value1, Integer value2) {
            addCriterion("book_id not between", value1, value2, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookNameIsNull() {
            addCriterion("book_name is null");
            return (Criteria) this;
        }

        public Criteria andBookNameIsNotNull() {
            addCriterion("book_name is not null");
            return (Criteria) this;
        }

        public Criteria andBookNameEqualTo(String value) {
            addCriterion("book_name =", value, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameNotEqualTo(String value) {
            addCriterion("book_name <>", value, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameGreaterThan(String value) {
            addCriterion("book_name >", value, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameGreaterThanOrEqualTo(String value) {
            addCriterion("book_name >=", value, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameLessThan(String value) {
            addCriterion("book_name <", value, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameLessThanOrEqualTo(String value) {
            addCriterion("book_name <=", value, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameLike(String value) {
            addCriterion("book_name like", value, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameNotLike(String value) {
            addCriterion("book_name not like", value, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameIn(List<String> values) {
            addCriterion("book_name in", values, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameNotIn(List<String> values) {
            addCriterion("book_name not in", values, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameBetween(String value1, String value2) {
            addCriterion("book_name between", value1, value2, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameNotBetween(String value1, String value2) {
            addCriterion("book_name not between", value1, value2, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookAuthorIsNull() {
            addCriterion("book_author is null");
            return (Criteria) this;
        }

        public Criteria andBookAuthorIsNotNull() {
            addCriterion("book_author is not null");
            return (Criteria) this;
        }

        public Criteria andBookAuthorEqualTo(String value) {
            addCriterion("book_author =", value, "bookAuthor");
            return (Criteria) this;
        }

        public Criteria andBookAuthorNotEqualTo(String value) {
            addCriterion("book_author <>", value, "bookAuthor");
            return (Criteria) this;
        }

        public Criteria andBookAuthorGreaterThan(String value) {
            addCriterion("book_author >", value, "bookAuthor");
            return (Criteria) this;
        }

        public Criteria andBookAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("book_author >=", value, "bookAuthor");
            return (Criteria) this;
        }

        public Criteria andBookAuthorLessThan(String value) {
            addCriterion("book_author <", value, "bookAuthor");
            return (Criteria) this;
        }

        public Criteria andBookAuthorLessThanOrEqualTo(String value) {
            addCriterion("book_author <=", value, "bookAuthor");
            return (Criteria) this;
        }

        public Criteria andBookAuthorLike(String value) {
            addCriterion("book_author like", value, "bookAuthor");
            return (Criteria) this;
        }

        public Criteria andBookAuthorNotLike(String value) {
            addCriterion("book_author not like", value, "bookAuthor");
            return (Criteria) this;
        }

        public Criteria andBookAuthorIn(List<String> values) {
            addCriterion("book_author in", values, "bookAuthor");
            return (Criteria) this;
        }

        public Criteria andBookAuthorNotIn(List<String> values) {
            addCriterion("book_author not in", values, "bookAuthor");
            return (Criteria) this;
        }

        public Criteria andBookAuthorBetween(String value1, String value2) {
            addCriterion("book_author between", value1, value2, "bookAuthor");
            return (Criteria) this;
        }

        public Criteria andBookAuthorNotBetween(String value1, String value2) {
            addCriterion("book_author not between", value1, value2, "bookAuthor");
            return (Criteria) this;
        }

        public Criteria andBookTypeIsNull() {
            addCriterion("book_type is null");
            return (Criteria) this;
        }

        public Criteria andBookTypeIsNotNull() {
            addCriterion("book_type is not null");
            return (Criteria) this;
        }

        public Criteria andBookTypeEqualTo(String value) {
            addCriterion("book_type =", value, "bookType");
            return (Criteria) this;
        }

        public Criteria andBookTypeNotEqualTo(String value) {
            addCriterion("book_type <>", value, "bookType");
            return (Criteria) this;
        }

        public Criteria andBookTypeGreaterThan(String value) {
            addCriterion("book_type >", value, "bookType");
            return (Criteria) this;
        }

        public Criteria andBookTypeGreaterThanOrEqualTo(String value) {
            addCriterion("book_type >=", value, "bookType");
            return (Criteria) this;
        }

        public Criteria andBookTypeLessThan(String value) {
            addCriterion("book_type <", value, "bookType");
            return (Criteria) this;
        }

        public Criteria andBookTypeLessThanOrEqualTo(String value) {
            addCriterion("book_type <=", value, "bookType");
            return (Criteria) this;
        }

        public Criteria andBookTypeLike(String value) {
            addCriterion("book_type like", value, "bookType");
            return (Criteria) this;
        }

        public Criteria andBookTypeNotLike(String value) {
            addCriterion("book_type not like", value, "bookType");
            return (Criteria) this;
        }

        public Criteria andBookTypeIn(List<String> values) {
            addCriterion("book_type in", values, "bookType");
            return (Criteria) this;
        }

        public Criteria andBookTypeNotIn(List<String> values) {
            addCriterion("book_type not in", values, "bookType");
            return (Criteria) this;
        }

        public Criteria andBookTypeBetween(String value1, String value2) {
            addCriterion("book_type between", value1, value2, "bookType");
            return (Criteria) this;
        }

        public Criteria andBookTypeNotBetween(String value1, String value2) {
            addCriterion("book_type not between", value1, value2, "bookType");
            return (Criteria) this;
        }

        public Criteria andWordNumIsNull() {
            addCriterion("word_num is null");
            return (Criteria) this;
        }

        public Criteria andWordNumIsNotNull() {
            addCriterion("word_num is not null");
            return (Criteria) this;
        }

        public Criteria andWordNumEqualTo(String value) {
            addCriterion("word_num =", value, "wordNum");
            return (Criteria) this;
        }

        public Criteria andWordNumNotEqualTo(String value) {
            addCriterion("word_num <>", value, "wordNum");
            return (Criteria) this;
        }

        public Criteria andWordNumGreaterThan(String value) {
            addCriterion("word_num >", value, "wordNum");
            return (Criteria) this;
        }

        public Criteria andWordNumGreaterThanOrEqualTo(String value) {
            addCriterion("word_num >=", value, "wordNum");
            return (Criteria) this;
        }

        public Criteria andWordNumLessThan(String value) {
            addCriterion("word_num <", value, "wordNum");
            return (Criteria) this;
        }

        public Criteria andWordNumLessThanOrEqualTo(String value) {
            addCriterion("word_num <=", value, "wordNum");
            return (Criteria) this;
        }

        public Criteria andWordNumLike(String value) {
            addCriterion("word_num like", value, "wordNum");
            return (Criteria) this;
        }

        public Criteria andWordNumNotLike(String value) {
            addCriterion("word_num not like", value, "wordNum");
            return (Criteria) this;
        }

        public Criteria andWordNumIn(List<String> values) {
            addCriterion("word_num in", values, "wordNum");
            return (Criteria) this;
        }

        public Criteria andWordNumNotIn(List<String> values) {
            addCriterion("word_num not in", values, "wordNum");
            return (Criteria) this;
        }

        public Criteria andWordNumBetween(String value1, String value2) {
            addCriterion("word_num between", value1, value2, "wordNum");
            return (Criteria) this;
        }

        public Criteria andWordNumNotBetween(String value1, String value2) {
            addCriterion("word_num not between", value1, value2, "wordNum");
            return (Criteria) this;
        }

        public Criteria andStatuIsNull() {
            addCriterion("Statu is null");
            return (Criteria) this;
        }

        public Criteria andStatuIsNotNull() {
            addCriterion("Statu is not null");
            return (Criteria) this;
        }

        public Criteria andStatuEqualTo(String value) {
            addCriterion("Statu =", value, "statu");
            return (Criteria) this;
        }

        public Criteria andStatuNotEqualTo(String value) {
            addCriterion("Statu <>", value, "statu");
            return (Criteria) this;
        }

        public Criteria andStatuGreaterThan(String value) {
            addCriterion("Statu >", value, "statu");
            return (Criteria) this;
        }

        public Criteria andStatuGreaterThanOrEqualTo(String value) {
            addCriterion("Statu >=", value, "statu");
            return (Criteria) this;
        }

        public Criteria andStatuLessThan(String value) {
            addCriterion("Statu <", value, "statu");
            return (Criteria) this;
        }

        public Criteria andStatuLessThanOrEqualTo(String value) {
            addCriterion("Statu <=", value, "statu");
            return (Criteria) this;
        }

        public Criteria andStatuLike(String value) {
            addCriterion("Statu like", value, "statu");
            return (Criteria) this;
        }

        public Criteria andStatuNotLike(String value) {
            addCriterion("Statu not like", value, "statu");
            return (Criteria) this;
        }

        public Criteria andStatuIn(List<String> values) {
            addCriterion("Statu in", values, "statu");
            return (Criteria) this;
        }

        public Criteria andStatuNotIn(List<String> values) {
            addCriterion("Statu not in", values, "statu");
            return (Criteria) this;
        }

        public Criteria andStatuBetween(String value1, String value2) {
            addCriterion("Statu between", value1, value2, "statu");
            return (Criteria) this;
        }

        public Criteria andStatuNotBetween(String value1, String value2) {
            addCriterion("Statu not between", value1, value2, "statu");
            return (Criteria) this;
        }

        public Criteria andBookInformationIsNull() {
            addCriterion("book_information is null");
            return (Criteria) this;
        }

        public Criteria andBookInformationIsNotNull() {
            addCriterion("book_information is not null");
            return (Criteria) this;
        }

        public Criteria andBookInformationEqualTo(String value) {
            addCriterion("book_information =", value, "bookInformation");
            return (Criteria) this;
        }

        public Criteria andBookInformationNotEqualTo(String value) {
            addCriterion("book_information <>", value, "bookInformation");
            return (Criteria) this;
        }

        public Criteria andBookInformationGreaterThan(String value) {
            addCriterion("book_information >", value, "bookInformation");
            return (Criteria) this;
        }

        public Criteria andBookInformationGreaterThanOrEqualTo(String value) {
            addCriterion("book_information >=", value, "bookInformation");
            return (Criteria) this;
        }

        public Criteria andBookInformationLessThan(String value) {
            addCriterion("book_information <", value, "bookInformation");
            return (Criteria) this;
        }

        public Criteria andBookInformationLessThanOrEqualTo(String value) {
            addCriterion("book_information <=", value, "bookInformation");
            return (Criteria) this;
        }

        public Criteria andBookInformationLike(String value) {
            addCriterion("book_information like", value, "bookInformation");
            return (Criteria) this;
        }

        public Criteria andBookInformationNotLike(String value) {
            addCriterion("book_information not like", value, "bookInformation");
            return (Criteria) this;
        }

        public Criteria andBookInformationIn(List<String> values) {
            addCriterion("book_information in", values, "bookInformation");
            return (Criteria) this;
        }

        public Criteria andBookInformationNotIn(List<String> values) {
            addCriterion("book_information not in", values, "bookInformation");
            return (Criteria) this;
        }

        public Criteria andBookInformationBetween(String value1, String value2) {
            addCriterion("book_information between", value1, value2, "bookInformation");
            return (Criteria) this;
        }

        public Criteria andBookInformationNotBetween(String value1, String value2) {
            addCriterion("book_information not between", value1, value2, "bookInformation");
            return (Criteria) this;
        }

        public Criteria andBookLable0IsNull() {
            addCriterion("book_lable0 is null");
            return (Criteria) this;
        }

        public Criteria andBookLable0IsNotNull() {
            addCriterion("book_lable0 is not null");
            return (Criteria) this;
        }

        public Criteria andBookLable0EqualTo(String value) {
            addCriterion("book_lable0 =", value, "bookLable0");
            return (Criteria) this;
        }

        public Criteria andBookLable0NotEqualTo(String value) {
            addCriterion("book_lable0 <>", value, "bookLable0");
            return (Criteria) this;
        }

        public Criteria andBookLable0GreaterThan(String value) {
            addCriterion("book_lable0 >", value, "bookLable0");
            return (Criteria) this;
        }

        public Criteria andBookLable0GreaterThanOrEqualTo(String value) {
            addCriterion("book_lable0 >=", value, "bookLable0");
            return (Criteria) this;
        }

        public Criteria andBookLable0LessThan(String value) {
            addCriterion("book_lable0 <", value, "bookLable0");
            return (Criteria) this;
        }

        public Criteria andBookLable0LessThanOrEqualTo(String value) {
            addCriterion("book_lable0 <=", value, "bookLable0");
            return (Criteria) this;
        }

        public Criteria andBookLable0Like(String value) {
            addCriterion("book_lable0 like", value, "bookLable0");
            return (Criteria) this;
        }

        public Criteria andBookLable0NotLike(String value) {
            addCriterion("book_lable0 not like", value, "bookLable0");
            return (Criteria) this;
        }

        public Criteria andBookLable0In(List<String> values) {
            addCriterion("book_lable0 in", values, "bookLable0");
            return (Criteria) this;
        }

        public Criteria andBookLable0NotIn(List<String> values) {
            addCriterion("book_lable0 not in", values, "bookLable0");
            return (Criteria) this;
        }

        public Criteria andBookLable0Between(String value1, String value2) {
            addCriterion("book_lable0 between", value1, value2, "bookLable0");
            return (Criteria) this;
        }

        public Criteria andBookLable0NotBetween(String value1, String value2) {
            addCriterion("book_lable0 not between", value1, value2, "bookLable0");
            return (Criteria) this;
        }

        public Criteria andBookLable1IsNull() {
            addCriterion("book_lable1 is null");
            return (Criteria) this;
        }

        public Criteria andBookLable1IsNotNull() {
            addCriterion("book_lable1 is not null");
            return (Criteria) this;
        }

        public Criteria andBookLable1EqualTo(String value) {
            addCriterion("book_lable1 =", value, "bookLable1");
            return (Criteria) this;
        }

        public Criteria andBookLable1NotEqualTo(String value) {
            addCriterion("book_lable1 <>", value, "bookLable1");
            return (Criteria) this;
        }

        public Criteria andBookLable1GreaterThan(String value) {
            addCriterion("book_lable1 >", value, "bookLable1");
            return (Criteria) this;
        }

        public Criteria andBookLable1GreaterThanOrEqualTo(String value) {
            addCriterion("book_lable1 >=", value, "bookLable1");
            return (Criteria) this;
        }

        public Criteria andBookLable1LessThan(String value) {
            addCriterion("book_lable1 <", value, "bookLable1");
            return (Criteria) this;
        }

        public Criteria andBookLable1LessThanOrEqualTo(String value) {
            addCriterion("book_lable1 <=", value, "bookLable1");
            return (Criteria) this;
        }

        public Criteria andBookLable1Like(String value) {
            addCriterion("book_lable1 like", value, "bookLable1");
            return (Criteria) this;
        }

        public Criteria andBookLable1NotLike(String value) {
            addCriterion("book_lable1 not like", value, "bookLable1");
            return (Criteria) this;
        }

        public Criteria andBookLable1In(List<String> values) {
            addCriterion("book_lable1 in", values, "bookLable1");
            return (Criteria) this;
        }

        public Criteria andBookLable1NotIn(List<String> values) {
            addCriterion("book_lable1 not in", values, "bookLable1");
            return (Criteria) this;
        }

        public Criteria andBookLable1Between(String value1, String value2) {
            addCriterion("book_lable1 between", value1, value2, "bookLable1");
            return (Criteria) this;
        }

        public Criteria andBookLable1NotBetween(String value1, String value2) {
            addCriterion("book_lable1 not between", value1, value2, "bookLable1");
            return (Criteria) this;
        }

        public Criteria andBookLable2IsNull() {
            addCriterion("book_lable2 is null");
            return (Criteria) this;
        }

        public Criteria andBookLable2IsNotNull() {
            addCriterion("book_lable2 is not null");
            return (Criteria) this;
        }

        public Criteria andBookLable2EqualTo(String value) {
            addCriterion("book_lable2 =", value, "bookLable2");
            return (Criteria) this;
        }

        public Criteria andBookLable2NotEqualTo(String value) {
            addCriterion("book_lable2 <>", value, "bookLable2");
            return (Criteria) this;
        }

        public Criteria andBookLable2GreaterThan(String value) {
            addCriterion("book_lable2 >", value, "bookLable2");
            return (Criteria) this;
        }

        public Criteria andBookLable2GreaterThanOrEqualTo(String value) {
            addCriterion("book_lable2 >=", value, "bookLable2");
            return (Criteria) this;
        }

        public Criteria andBookLable2LessThan(String value) {
            addCriterion("book_lable2 <", value, "bookLable2");
            return (Criteria) this;
        }

        public Criteria andBookLable2LessThanOrEqualTo(String value) {
            addCriterion("book_lable2 <=", value, "bookLable2");
            return (Criteria) this;
        }

        public Criteria andBookLable2Like(String value) {
            addCriterion("book_lable2 like", value, "bookLable2");
            return (Criteria) this;
        }

        public Criteria andBookLable2NotLike(String value) {
            addCriterion("book_lable2 not like", value, "bookLable2");
            return (Criteria) this;
        }

        public Criteria andBookLable2In(List<String> values) {
            addCriterion("book_lable2 in", values, "bookLable2");
            return (Criteria) this;
        }

        public Criteria andBookLable2NotIn(List<String> values) {
            addCriterion("book_lable2 not in", values, "bookLable2");
            return (Criteria) this;
        }

        public Criteria andBookLable2Between(String value1, String value2) {
            addCriterion("book_lable2 between", value1, value2, "bookLable2");
            return (Criteria) this;
        }

        public Criteria andBookLable2NotBetween(String value1, String value2) {
            addCriterion("book_lable2 not between", value1, value2, "bookLable2");
            return (Criteria) this;
        }

        public Criteria andBookLable3IsNull() {
            addCriterion("book_lable3 is null");
            return (Criteria) this;
        }

        public Criteria andBookLable3IsNotNull() {
            addCriterion("book_lable3 is not null");
            return (Criteria) this;
        }

        public Criteria andBookLable3EqualTo(String value) {
            addCriterion("book_lable3 =", value, "bookLable3");
            return (Criteria) this;
        }

        public Criteria andBookLable3NotEqualTo(String value) {
            addCriterion("book_lable3 <>", value, "bookLable3");
            return (Criteria) this;
        }

        public Criteria andBookLable3GreaterThan(String value) {
            addCriterion("book_lable3 >", value, "bookLable3");
            return (Criteria) this;
        }

        public Criteria andBookLable3GreaterThanOrEqualTo(String value) {
            addCriterion("book_lable3 >=", value, "bookLable3");
            return (Criteria) this;
        }

        public Criteria andBookLable3LessThan(String value) {
            addCriterion("book_lable3 <", value, "bookLable3");
            return (Criteria) this;
        }

        public Criteria andBookLable3LessThanOrEqualTo(String value) {
            addCriterion("book_lable3 <=", value, "bookLable3");
            return (Criteria) this;
        }

        public Criteria andBookLable3Like(String value) {
            addCriterion("book_lable3 like", value, "bookLable3");
            return (Criteria) this;
        }

        public Criteria andBookLable3NotLike(String value) {
            addCriterion("book_lable3 not like", value, "bookLable3");
            return (Criteria) this;
        }

        public Criteria andBookLable3In(List<String> values) {
            addCriterion("book_lable3 in", values, "bookLable3");
            return (Criteria) this;
        }

        public Criteria andBookLable3NotIn(List<String> values) {
            addCriterion("book_lable3 not in", values, "bookLable3");
            return (Criteria) this;
        }

        public Criteria andBookLable3Between(String value1, String value2) {
            addCriterion("book_lable3 between", value1, value2, "bookLable3");
            return (Criteria) this;
        }

        public Criteria andBookLable3NotBetween(String value1, String value2) {
            addCriterion("book_lable3 not between", value1, value2, "bookLable3");
            return (Criteria) this;
        }

        public Criteria andBookLable4IsNull() {
            addCriterion("book_lable4 is null");
            return (Criteria) this;
        }

        public Criteria andBookLable4IsNotNull() {
            addCriterion("book_lable4 is not null");
            return (Criteria) this;
        }

        public Criteria andBookLable4EqualTo(String value) {
            addCriterion("book_lable4 =", value, "bookLable4");
            return (Criteria) this;
        }

        public Criteria andBookLable4NotEqualTo(String value) {
            addCriterion("book_lable4 <>", value, "bookLable4");
            return (Criteria) this;
        }

        public Criteria andBookLable4GreaterThan(String value) {
            addCriterion("book_lable4 >", value, "bookLable4");
            return (Criteria) this;
        }

        public Criteria andBookLable4GreaterThanOrEqualTo(String value) {
            addCriterion("book_lable4 >=", value, "bookLable4");
            return (Criteria) this;
        }

        public Criteria andBookLable4LessThan(String value) {
            addCriterion("book_lable4 <", value, "bookLable4");
            return (Criteria) this;
        }

        public Criteria andBookLable4LessThanOrEqualTo(String value) {
            addCriterion("book_lable4 <=", value, "bookLable4");
            return (Criteria) this;
        }

        public Criteria andBookLable4Like(String value) {
            addCriterion("book_lable4 like", value, "bookLable4");
            return (Criteria) this;
        }

        public Criteria andBookLable4NotLike(String value) {
            addCriterion("book_lable4 not like", value, "bookLable4");
            return (Criteria) this;
        }

        public Criteria andBookLable4In(List<String> values) {
            addCriterion("book_lable4 in", values, "bookLable4");
            return (Criteria) this;
        }

        public Criteria andBookLable4NotIn(List<String> values) {
            addCriterion("book_lable4 not in", values, "bookLable4");
            return (Criteria) this;
        }

        public Criteria andBookLable4Between(String value1, String value2) {
            addCriterion("book_lable4 between", value1, value2, "bookLable4");
            return (Criteria) this;
        }

        public Criteria andBookLable4NotBetween(String value1, String value2) {
            addCriterion("book_lable4 not between", value1, value2, "bookLable4");
            return (Criteria) this;
        }

        public Criteria andPhoto1IsNull() {
            addCriterion("photo1 is null");
            return (Criteria) this;
        }

        public Criteria andPhoto1IsNotNull() {
            addCriterion("photo1 is not null");
            return (Criteria) this;
        }

        public Criteria andPhoto1EqualTo(String value) {
            addCriterion("photo1 =", value, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1NotEqualTo(String value) {
            addCriterion("photo1 <>", value, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1GreaterThan(String value) {
            addCriterion("photo1 >", value, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1GreaterThanOrEqualTo(String value) {
            addCriterion("photo1 >=", value, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1LessThan(String value) {
            addCriterion("photo1 <", value, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1LessThanOrEqualTo(String value) {
            addCriterion("photo1 <=", value, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1Like(String value) {
            addCriterion("photo1 like", value, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1NotLike(String value) {
            addCriterion("photo1 not like", value, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1In(List<String> values) {
            addCriterion("photo1 in", values, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1NotIn(List<String> values) {
            addCriterion("photo1 not in", values, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1Between(String value1, String value2) {
            addCriterion("photo1 between", value1, value2, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1NotBetween(String value1, String value2) {
            addCriterion("photo1 not between", value1, value2, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto2IsNull() {
            addCriterion("photo2 is null");
            return (Criteria) this;
        }

        public Criteria andPhoto2IsNotNull() {
            addCriterion("photo2 is not null");
            return (Criteria) this;
        }

        public Criteria andPhoto2EqualTo(String value) {
            addCriterion("photo2 =", value, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2NotEqualTo(String value) {
            addCriterion("photo2 <>", value, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2GreaterThan(String value) {
            addCriterion("photo2 >", value, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2GreaterThanOrEqualTo(String value) {
            addCriterion("photo2 >=", value, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2LessThan(String value) {
            addCriterion("photo2 <", value, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2LessThanOrEqualTo(String value) {
            addCriterion("photo2 <=", value, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2Like(String value) {
            addCriterion("photo2 like", value, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2NotLike(String value) {
            addCriterion("photo2 not like", value, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2In(List<String> values) {
            addCriterion("photo2 in", values, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2NotIn(List<String> values) {
            addCriterion("photo2 not in", values, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2Between(String value1, String value2) {
            addCriterion("photo2 between", value1, value2, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2NotBetween(String value1, String value2) {
            addCriterion("photo2 not between", value1, value2, "photo2");
            return (Criteria) this;
        }

        public Criteria andCoverpathIsNull() {
            addCriterion("coverpath is null");
            return (Criteria) this;
        }

        public Criteria andCoverpathIsNotNull() {
            addCriterion("coverpath is not null");
            return (Criteria) this;
        }

        public Criteria andCoverpathEqualTo(String value) {
            addCriterion("coverpath =", value, "coverpath");
            return (Criteria) this;
        }

        public Criteria andCoverpathNotEqualTo(String value) {
            addCriterion("coverpath <>", value, "coverpath");
            return (Criteria) this;
        }

        public Criteria andCoverpathGreaterThan(String value) {
            addCriterion("coverpath >", value, "coverpath");
            return (Criteria) this;
        }

        public Criteria andCoverpathGreaterThanOrEqualTo(String value) {
            addCriterion("coverpath >=", value, "coverpath");
            return (Criteria) this;
        }

        public Criteria andCoverpathLessThan(String value) {
            addCriterion("coverpath <", value, "coverpath");
            return (Criteria) this;
        }

        public Criteria andCoverpathLessThanOrEqualTo(String value) {
            addCriterion("coverpath <=", value, "coverpath");
            return (Criteria) this;
        }

        public Criteria andCoverpathLike(String value) {
            addCriterion("coverpath like", value, "coverpath");
            return (Criteria) this;
        }

        public Criteria andCoverpathNotLike(String value) {
            addCriterion("coverpath not like", value, "coverpath");
            return (Criteria) this;
        }

        public Criteria andCoverpathIn(List<String> values) {
            addCriterion("coverpath in", values, "coverpath");
            return (Criteria) this;
        }

        public Criteria andCoverpathNotIn(List<String> values) {
            addCriterion("coverpath not in", values, "coverpath");
            return (Criteria) this;
        }

        public Criteria andCoverpathBetween(String value1, String value2) {
            addCriterion("coverpath between", value1, value2, "coverpath");
            return (Criteria) this;
        }

        public Criteria andCoverpathNotBetween(String value1, String value2) {
            addCriterion("coverpath not between", value1, value2, "coverpath");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table book
     *
     * @mbg.generated do_not_delete_during_merge Sat Nov 30 19:12:40 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table book
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}