package com.example.design.common.domain;

public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_id
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_name
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    private String bookName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_author
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    private String bookAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_type
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    private String bookType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.word_num
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    private String wordNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.Statu
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    private String statu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_information
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    private String bookInformation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_lable0
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    private String bookLable0;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_lable1
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    private String bookLable1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_lable2
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    private String bookLable2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_lable3
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    private String bookLable3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_lable4
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    private String bookLable4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.photo1
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    private String photo1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.photo2
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    private String photo2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.coverpath
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    private String coverpath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_id
     *
     * @return the value of book.book_id
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_id
     *
     * @param bookId the value for book.book_id
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_name
     *
     * @return the value of book.book_name
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_name
     *
     * @param bookName the value for book.book_name
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_author
     *
     * @return the value of book.book_author
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public String getBookAuthor() {
        return bookAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_author
     *
     * @param bookAuthor the value for book.book_author
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public void setBookAuthor(String bookAuthor) {
        this.bookAuthor = bookAuthor == null ? null : bookAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_type
     *
     * @return the value of book.book_type
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public String getBookType() {
        return bookType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_type
     *
     * @param bookType the value for book.book_type
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public void setBookType(String bookType) {
        this.bookType = bookType == null ? null : bookType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.word_num
     *
     * @return the value of book.word_num
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public String getWordNum() {
        return wordNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.word_num
     *
     * @param wordNum the value for book.word_num
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public void setWordNum(String wordNum) {
        this.wordNum = wordNum == null ? null : wordNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.Statu
     *
     * @return the value of book.Statu
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public String getStatu() {
        return statu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.Statu
     *
     * @param statu the value for book.Statu
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public void setStatu(String statu) {
        this.statu = statu == null ? null : statu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_information
     *
     * @return the value of book.book_information
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public String getBookInformation() {
        return bookInformation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_information
     *
     * @param bookInformation the value for book.book_information
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public void setBookInformation(String bookInformation) {
        this.bookInformation = bookInformation == null ? null : bookInformation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_lable0
     *
     * @return the value of book.book_lable0
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public String getBookLable0() {
        return bookLable0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_lable0
     *
     * @param bookLable0 the value for book.book_lable0
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public void setBookLable0(String bookLable0) {
        this.bookLable0 = bookLable0 == null ? null : bookLable0.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_lable1
     *
     * @return the value of book.book_lable1
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public String getBookLable1() {
        return bookLable1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_lable1
     *
     * @param bookLable1 the value for book.book_lable1
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public void setBookLable1(String bookLable1) {
        this.bookLable1 = bookLable1 == null ? null : bookLable1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_lable2
     *
     * @return the value of book.book_lable2
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public String getBookLable2() {
        return bookLable2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_lable2
     *
     * @param bookLable2 the value for book.book_lable2
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public void setBookLable2(String bookLable2) {
        this.bookLable2 = bookLable2 == null ? null : bookLable2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_lable3
     *
     * @return the value of book.book_lable3
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public String getBookLable3() {
        return bookLable3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_lable3
     *
     * @param bookLable3 the value for book.book_lable3
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public void setBookLable3(String bookLable3) {
        this.bookLable3 = bookLable3 == null ? null : bookLable3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_lable4
     *
     * @return the value of book.book_lable4
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public String getBookLable4() {
        return bookLable4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_lable4
     *
     * @param bookLable4 the value for book.book_lable4
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public void setBookLable4(String bookLable4) {
        this.bookLable4 = bookLable4 == null ? null : bookLable4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.photo1
     *
     * @return the value of book.photo1
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public String getPhoto1() {
        return photo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.photo1
     *
     * @param photo1 the value for book.photo1
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public void setPhoto1(String photo1) {
        this.photo1 = photo1 == null ? null : photo1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.photo2
     *
     * @return the value of book.photo2
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public String getPhoto2() {
        return photo2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.photo2
     *
     * @param photo2 the value for book.photo2
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public void setPhoto2(String photo2) {
        this.photo2 = photo2 == null ? null : photo2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.coverpath
     *
     * @return the value of book.coverpath
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public String getCoverpath() {
        return coverpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.coverpath
     *
     * @param coverpath the value for book.coverpath
     *
     * @mbg.generated Sat Nov 30 19:12:40 CST 2019
     */
    public void setCoverpath(String coverpath) {
        this.coverpath = coverpath == null ? null : coverpath.trim();
    }
}