spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/design?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
  freemarker:
    check-template-location: false
  thymeleaf:
    cache: false
server:
  port: 8888
  address: localhost
mybatis:
  mapper-locations: "classpath:/mybatis/mapper/*.xml"
logging:
level:
    com.example.design.mapper: DEBUG
