package com.example.design.mapper;

import com.example.design.common.domain.Bookshelf;
import com.example.design.common.domain.BookshelfExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookshelfMapper {
    List<Bookshelf> finds(String  telephone);
    List<Bookshelf> yzshelf(@Param("bookid") Integer bookid,@Param("telephone") String telephone);
    int delshelf(@Param("bookid") Integer bookid,@Param("telephone") String telephone);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 08 11:15:03 CST 2019
     */
    long countByExample(BookshelfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 08 11:15:03 CST 2019
     */
    int deleteByExample(BookshelfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 08 11:15:03 CST 2019
     */
    int deleteByPrimaryKey(Integer shelfid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 08 11:15:03 CST 2019
     */
    int insert(Bookshelf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 08 11:15:03 CST 2019
     */
    int insertSelective(Bookshelf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 08 11:15:03 CST 2019
     */
    List<Bookshelf> selectByExample(BookshelfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 08 11:15:03 CST 2019
     */
    Bookshelf selectByPrimaryKey(Integer shelfid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 08 11:15:03 CST 2019
     */
    int updateByExampleSelective(@Param("record") Bookshelf record, @Param("example") BookshelfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 08 11:15:03 CST 2019
     */
    int updateByExample(@Param("record") Bookshelf record, @Param("example") BookshelfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 08 11:15:03 CST 2019
     */
    int updateByPrimaryKeySelective(Bookshelf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Dec 08 11:15:03 CST 2019
     */
    int updateByPrimaryKey(Bookshelf record);
}